version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 8091:8000
    volumes:
      - ./:/app
      - node_modules_volume:/app/node_modules
    tty: true
    stdin_open: true

volumes:
  node_modules_volume: